// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class addedmorebookfields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedmorebookfields));
        
        string IMigrationMetadata.Id
        {
            get { return "201412222225441_added more book fields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
